services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    env_file:
      - .env.development
    image: with-docker-multi-env-development
    ports:
      - "5001:5000"
    restart: unless-stopped
